name: GoVulnCheck

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.21.3
          go-package: ./...
